gen_keys:
    #!/usr/bin/sh
    rm -rf cred
    mkdir cred
    cd cred
    openssl ecparam -name prime256v1 -genkey -outform DER -out private.der
    openssl ec -inform DER -in private.der -outform PEM -out private.pem
    openssl ec -inform DER -in private.der -pubout -outform DER -out public.der
    openssl ec -inform PEM -in private.pem -pubout -outform PEM -out public.pem
    touch summary.txt
    cat private.pem >> summary.txt
    xxd -i private.der >> summary.txt
    cat public.pem >> summary.txt
    xxd -i public.der >> summary.txt
    cd ..
    rm -rf cred.h
    touch cred.h
    echo "#pragma once" > cred.h
    echo "" >> cred.h
    xxd -i cred/private.der >> cred.h
    echo "" >> cred.h
    xxd -i cred/public.der >> cred.h
