# Warning: Only works with specific configurations. E.g. with the default nftables config.
#          On my system (Valentin), this rule always gets reset, so I implemented this small command.
open_firewall:
    #!/usr/bin/sh
    sudo nft add rule inet filter input position 9 udp dport 5684 accept

gen_keys:
    #!/usr/bin/sh
    rm -rf cred
    mkdir cred
    cd cred
    openssl ecparam -name prime256v1 -noout -genkey -outform PEM -out private.pem
    openssl req -x509 -nodes -key private.pem -out cert.pem -config ../cred.conf
