APPLICATION = sensor

RIOTBASE ?= $(CURDIR)/../../Tutorials/RIOT
RIOTTOOLS ?= $(RIOTBASE)/dist/tools

BOARD ?= samr21-xpro

# general
USEMODULE += periph_adc
USEMODULE += ps
USEMODULE += shell
USEMODULE += shell_commands
USEMODULE += ztimer
USEMODULE += ztimer_msec

include $(RIOTBASE)/Makefile.include
